
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Aeronave` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Aeronave
 * 
 */
export type AeronaveModel = runtime.Types.Result.DefaultSelection<Prisma.$AeronavePayload>

export type AggregateAeronave = {
  _count: AeronaveCountAggregateOutputType | null
  _avg: AeronaveAvgAggregateOutputType | null
  _sum: AeronaveSumAggregateOutputType | null
  _min: AeronaveMinAggregateOutputType | null
  _max: AeronaveMaxAggregateOutputType | null
}

export type AeronaveAvgAggregateOutputType = {
  id: number | null
  horas: number | null
}

export type AeronaveSumAggregateOutputType = {
  id: number | null
  horas: number | null
}

export type AeronaveMinAggregateOutputType = {
  id: number | null
  matricula: string | null
  modelo: string | null
  estado: string | null
  horas: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AeronaveMaxAggregateOutputType = {
  id: number | null
  matricula: string | null
  modelo: string | null
  estado: string | null
  horas: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AeronaveCountAggregateOutputType = {
  id: number
  matricula: number
  modelo: number
  estado: number
  horas: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AeronaveAvgAggregateInputType = {
  id?: true
  horas?: true
}

export type AeronaveSumAggregateInputType = {
  id?: true
  horas?: true
}

export type AeronaveMinAggregateInputType = {
  id?: true
  matricula?: true
  modelo?: true
  estado?: true
  horas?: true
  createdAt?: true
  updatedAt?: true
}

export type AeronaveMaxAggregateInputType = {
  id?: true
  matricula?: true
  modelo?: true
  estado?: true
  horas?: true
  createdAt?: true
  updatedAt?: true
}

export type AeronaveCountAggregateInputType = {
  id?: true
  matricula?: true
  modelo?: true
  estado?: true
  horas?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AeronaveAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Aeronave to aggregate.
   */
  where?: Prisma.AeronaveWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Aeronaves to fetch.
   */
  orderBy?: Prisma.AeronaveOrderByWithRelationInput | Prisma.AeronaveOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AeronaveWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Aeronaves from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Aeronaves.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Aeronaves
  **/
  _count?: true | AeronaveCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AeronaveAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AeronaveSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AeronaveMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AeronaveMaxAggregateInputType
}

export type GetAeronaveAggregateType<T extends AeronaveAggregateArgs> = {
      [P in keyof T & keyof AggregateAeronave]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAeronave[P]>
    : Prisma.GetScalarType<T[P], AggregateAeronave[P]>
}




export type AeronaveGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AeronaveWhereInput
  orderBy?: Prisma.AeronaveOrderByWithAggregationInput | Prisma.AeronaveOrderByWithAggregationInput[]
  by: Prisma.AeronaveScalarFieldEnum[] | Prisma.AeronaveScalarFieldEnum
  having?: Prisma.AeronaveScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AeronaveCountAggregateInputType | true
  _avg?: AeronaveAvgAggregateInputType
  _sum?: AeronaveSumAggregateInputType
  _min?: AeronaveMinAggregateInputType
  _max?: AeronaveMaxAggregateInputType
}

export type AeronaveGroupByOutputType = {
  id: number
  matricula: string
  modelo: string
  estado: string
  horas: number
  createdAt: Date
  updatedAt: Date
  _count: AeronaveCountAggregateOutputType | null
  _avg: AeronaveAvgAggregateOutputType | null
  _sum: AeronaveSumAggregateOutputType | null
  _min: AeronaveMinAggregateOutputType | null
  _max: AeronaveMaxAggregateOutputType | null
}

type GetAeronaveGroupByPayload<T extends AeronaveGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AeronaveGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AeronaveGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AeronaveGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AeronaveGroupByOutputType[P]>
      }
    >
  >



export type AeronaveWhereInput = {
  AND?: Prisma.AeronaveWhereInput | Prisma.AeronaveWhereInput[]
  OR?: Prisma.AeronaveWhereInput[]
  NOT?: Prisma.AeronaveWhereInput | Prisma.AeronaveWhereInput[]
  id?: Prisma.IntFilter<"Aeronave"> | number
  matricula?: Prisma.StringFilter<"Aeronave"> | string
  modelo?: Prisma.StringFilter<"Aeronave"> | string
  estado?: Prisma.StringFilter<"Aeronave"> | string
  horas?: Prisma.IntFilter<"Aeronave"> | number
  createdAt?: Prisma.DateTimeFilter<"Aeronave"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Aeronave"> | Date | string
}

export type AeronaveOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  matricula?: Prisma.SortOrder
  modelo?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  horas?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AeronaveWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  matricula?: string
  AND?: Prisma.AeronaveWhereInput | Prisma.AeronaveWhereInput[]
  OR?: Prisma.AeronaveWhereInput[]
  NOT?: Prisma.AeronaveWhereInput | Prisma.AeronaveWhereInput[]
  modelo?: Prisma.StringFilter<"Aeronave"> | string
  estado?: Prisma.StringFilter<"Aeronave"> | string
  horas?: Prisma.IntFilter<"Aeronave"> | number
  createdAt?: Prisma.DateTimeFilter<"Aeronave"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Aeronave"> | Date | string
}, "id" | "matricula">

export type AeronaveOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  matricula?: Prisma.SortOrder
  modelo?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  horas?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AeronaveCountOrderByAggregateInput
  _avg?: Prisma.AeronaveAvgOrderByAggregateInput
  _max?: Prisma.AeronaveMaxOrderByAggregateInput
  _min?: Prisma.AeronaveMinOrderByAggregateInput
  _sum?: Prisma.AeronaveSumOrderByAggregateInput
}

export type AeronaveScalarWhereWithAggregatesInput = {
  AND?: Prisma.AeronaveScalarWhereWithAggregatesInput | Prisma.AeronaveScalarWhereWithAggregatesInput[]
  OR?: Prisma.AeronaveScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AeronaveScalarWhereWithAggregatesInput | Prisma.AeronaveScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Aeronave"> | number
  matricula?: Prisma.StringWithAggregatesFilter<"Aeronave"> | string
  modelo?: Prisma.StringWithAggregatesFilter<"Aeronave"> | string
  estado?: Prisma.StringWithAggregatesFilter<"Aeronave"> | string
  horas?: Prisma.IntWithAggregatesFilter<"Aeronave"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Aeronave"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Aeronave"> | Date | string
}

export type AeronaveCreateInput = {
  matricula: string
  modelo: string
  estado: string
  horas?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AeronaveUncheckedCreateInput = {
  id?: number
  matricula: string
  modelo: string
  estado: string
  horas?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AeronaveUpdateInput = {
  matricula?: Prisma.StringFieldUpdateOperationsInput | string
  modelo?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  horas?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AeronaveUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  matricula?: Prisma.StringFieldUpdateOperationsInput | string
  modelo?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  horas?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AeronaveCreateManyInput = {
  id?: number
  matricula: string
  modelo: string
  estado: string
  horas?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AeronaveUpdateManyMutationInput = {
  matricula?: Prisma.StringFieldUpdateOperationsInput | string
  modelo?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  horas?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AeronaveUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  matricula?: Prisma.StringFieldUpdateOperationsInput | string
  modelo?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  horas?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AeronaveCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  matricula?: Prisma.SortOrder
  modelo?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  horas?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AeronaveAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  horas?: Prisma.SortOrder
}

export type AeronaveMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  matricula?: Prisma.SortOrder
  modelo?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  horas?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AeronaveMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  matricula?: Prisma.SortOrder
  modelo?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  horas?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AeronaveSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  horas?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}



export type AeronaveSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  matricula?: boolean
  modelo?: boolean
  estado?: boolean
  horas?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["aeronave"]>

export type AeronaveSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  matricula?: boolean
  modelo?: boolean
  estado?: boolean
  horas?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["aeronave"]>

export type AeronaveSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  matricula?: boolean
  modelo?: boolean
  estado?: boolean
  horas?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["aeronave"]>

export type AeronaveSelectScalar = {
  id?: boolean
  matricula?: boolean
  modelo?: boolean
  estado?: boolean
  horas?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AeronaveOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "matricula" | "modelo" | "estado" | "horas" | "createdAt" | "updatedAt", ExtArgs["result"]["aeronave"]>

export type $AeronavePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Aeronave"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    matricula: string
    modelo: string
    estado: string
    horas: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["aeronave"]>
  composites: {}
}

export type AeronaveGetPayload<S extends boolean | null | undefined | AeronaveDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AeronavePayload, S>

export type AeronaveCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AeronaveFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AeronaveCountAggregateInputType | true
  }

export interface AeronaveDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Aeronave'], meta: { name: 'Aeronave' } }
  /**
   * Find zero or one Aeronave that matches the filter.
   * @param {AeronaveFindUniqueArgs} args - Arguments to find a Aeronave
   * @example
   * // Get one Aeronave
   * const aeronave = await prisma.aeronave.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AeronaveFindUniqueArgs>(args: Prisma.SelectSubset<T, AeronaveFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AeronaveClient<runtime.Types.Result.GetResult<Prisma.$AeronavePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Aeronave that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AeronaveFindUniqueOrThrowArgs} args - Arguments to find a Aeronave
   * @example
   * // Get one Aeronave
   * const aeronave = await prisma.aeronave.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AeronaveFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AeronaveFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AeronaveClient<runtime.Types.Result.GetResult<Prisma.$AeronavePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Aeronave that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AeronaveFindFirstArgs} args - Arguments to find a Aeronave
   * @example
   * // Get one Aeronave
   * const aeronave = await prisma.aeronave.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AeronaveFindFirstArgs>(args?: Prisma.SelectSubset<T, AeronaveFindFirstArgs<ExtArgs>>): Prisma.Prisma__AeronaveClient<runtime.Types.Result.GetResult<Prisma.$AeronavePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Aeronave that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AeronaveFindFirstOrThrowArgs} args - Arguments to find a Aeronave
   * @example
   * // Get one Aeronave
   * const aeronave = await prisma.aeronave.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AeronaveFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AeronaveFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AeronaveClient<runtime.Types.Result.GetResult<Prisma.$AeronavePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Aeronaves that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AeronaveFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Aeronaves
   * const aeronaves = await prisma.aeronave.findMany()
   * 
   * // Get first 10 Aeronaves
   * const aeronaves = await prisma.aeronave.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const aeronaveWithIdOnly = await prisma.aeronave.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AeronaveFindManyArgs>(args?: Prisma.SelectSubset<T, AeronaveFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AeronavePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Aeronave.
   * @param {AeronaveCreateArgs} args - Arguments to create a Aeronave.
   * @example
   * // Create one Aeronave
   * const Aeronave = await prisma.aeronave.create({
   *   data: {
   *     // ... data to create a Aeronave
   *   }
   * })
   * 
   */
  create<T extends AeronaveCreateArgs>(args: Prisma.SelectSubset<T, AeronaveCreateArgs<ExtArgs>>): Prisma.Prisma__AeronaveClient<runtime.Types.Result.GetResult<Prisma.$AeronavePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Aeronaves.
   * @param {AeronaveCreateManyArgs} args - Arguments to create many Aeronaves.
   * @example
   * // Create many Aeronaves
   * const aeronave = await prisma.aeronave.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AeronaveCreateManyArgs>(args?: Prisma.SelectSubset<T, AeronaveCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Aeronaves and returns the data saved in the database.
   * @param {AeronaveCreateManyAndReturnArgs} args - Arguments to create many Aeronaves.
   * @example
   * // Create many Aeronaves
   * const aeronave = await prisma.aeronave.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Aeronaves and only return the `id`
   * const aeronaveWithIdOnly = await prisma.aeronave.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AeronaveCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AeronaveCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AeronavePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Aeronave.
   * @param {AeronaveDeleteArgs} args - Arguments to delete one Aeronave.
   * @example
   * // Delete one Aeronave
   * const Aeronave = await prisma.aeronave.delete({
   *   where: {
   *     // ... filter to delete one Aeronave
   *   }
   * })
   * 
   */
  delete<T extends AeronaveDeleteArgs>(args: Prisma.SelectSubset<T, AeronaveDeleteArgs<ExtArgs>>): Prisma.Prisma__AeronaveClient<runtime.Types.Result.GetResult<Prisma.$AeronavePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Aeronave.
   * @param {AeronaveUpdateArgs} args - Arguments to update one Aeronave.
   * @example
   * // Update one Aeronave
   * const aeronave = await prisma.aeronave.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AeronaveUpdateArgs>(args: Prisma.SelectSubset<T, AeronaveUpdateArgs<ExtArgs>>): Prisma.Prisma__AeronaveClient<runtime.Types.Result.GetResult<Prisma.$AeronavePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Aeronaves.
   * @param {AeronaveDeleteManyArgs} args - Arguments to filter Aeronaves to delete.
   * @example
   * // Delete a few Aeronaves
   * const { count } = await prisma.aeronave.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AeronaveDeleteManyArgs>(args?: Prisma.SelectSubset<T, AeronaveDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Aeronaves.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AeronaveUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Aeronaves
   * const aeronave = await prisma.aeronave.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AeronaveUpdateManyArgs>(args: Prisma.SelectSubset<T, AeronaveUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Aeronaves and returns the data updated in the database.
   * @param {AeronaveUpdateManyAndReturnArgs} args - Arguments to update many Aeronaves.
   * @example
   * // Update many Aeronaves
   * const aeronave = await prisma.aeronave.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Aeronaves and only return the `id`
   * const aeronaveWithIdOnly = await prisma.aeronave.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AeronaveUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AeronaveUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AeronavePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Aeronave.
   * @param {AeronaveUpsertArgs} args - Arguments to update or create a Aeronave.
   * @example
   * // Update or create a Aeronave
   * const aeronave = await prisma.aeronave.upsert({
   *   create: {
   *     // ... data to create a Aeronave
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Aeronave we want to update
   *   }
   * })
   */
  upsert<T extends AeronaveUpsertArgs>(args: Prisma.SelectSubset<T, AeronaveUpsertArgs<ExtArgs>>): Prisma.Prisma__AeronaveClient<runtime.Types.Result.GetResult<Prisma.$AeronavePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Aeronaves.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AeronaveCountArgs} args - Arguments to filter Aeronaves to count.
   * @example
   * // Count the number of Aeronaves
   * const count = await prisma.aeronave.count({
   *   where: {
   *     // ... the filter for the Aeronaves we want to count
   *   }
   * })
  **/
  count<T extends AeronaveCountArgs>(
    args?: Prisma.Subset<T, AeronaveCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AeronaveCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Aeronave.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AeronaveAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AeronaveAggregateArgs>(args: Prisma.Subset<T, AeronaveAggregateArgs>): Prisma.PrismaPromise<GetAeronaveAggregateType<T>>

  /**
   * Group by Aeronave.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AeronaveGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AeronaveGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AeronaveGroupByArgs['orderBy'] }
      : { orderBy?: AeronaveGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AeronaveGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAeronaveGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Aeronave model
 */
readonly fields: AeronaveFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Aeronave.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AeronaveClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Aeronave model
 */
export interface AeronaveFieldRefs {
  readonly id: Prisma.FieldRef<"Aeronave", 'Int'>
  readonly matricula: Prisma.FieldRef<"Aeronave", 'String'>
  readonly modelo: Prisma.FieldRef<"Aeronave", 'String'>
  readonly estado: Prisma.FieldRef<"Aeronave", 'String'>
  readonly horas: Prisma.FieldRef<"Aeronave", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Aeronave", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Aeronave", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Aeronave findUnique
 */
export type AeronaveFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Aeronave
   */
  select?: Prisma.AeronaveSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Aeronave
   */
  omit?: Prisma.AeronaveOmit<ExtArgs> | null
  /**
   * Filter, which Aeronave to fetch.
   */
  where: Prisma.AeronaveWhereUniqueInput
}

/**
 * Aeronave findUniqueOrThrow
 */
export type AeronaveFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Aeronave
   */
  select?: Prisma.AeronaveSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Aeronave
   */
  omit?: Prisma.AeronaveOmit<ExtArgs> | null
  /**
   * Filter, which Aeronave to fetch.
   */
  where: Prisma.AeronaveWhereUniqueInput
}

/**
 * Aeronave findFirst
 */
export type AeronaveFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Aeronave
   */
  select?: Prisma.AeronaveSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Aeronave
   */
  omit?: Prisma.AeronaveOmit<ExtArgs> | null
  /**
   * Filter, which Aeronave to fetch.
   */
  where?: Prisma.AeronaveWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Aeronaves to fetch.
   */
  orderBy?: Prisma.AeronaveOrderByWithRelationInput | Prisma.AeronaveOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Aeronaves.
   */
  cursor?: Prisma.AeronaveWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Aeronaves from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Aeronaves.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Aeronaves.
   */
  distinct?: Prisma.AeronaveScalarFieldEnum | Prisma.AeronaveScalarFieldEnum[]
}

/**
 * Aeronave findFirstOrThrow
 */
export type AeronaveFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Aeronave
   */
  select?: Prisma.AeronaveSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Aeronave
   */
  omit?: Prisma.AeronaveOmit<ExtArgs> | null
  /**
   * Filter, which Aeronave to fetch.
   */
  where?: Prisma.AeronaveWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Aeronaves to fetch.
   */
  orderBy?: Prisma.AeronaveOrderByWithRelationInput | Prisma.AeronaveOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Aeronaves.
   */
  cursor?: Prisma.AeronaveWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Aeronaves from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Aeronaves.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Aeronaves.
   */
  distinct?: Prisma.AeronaveScalarFieldEnum | Prisma.AeronaveScalarFieldEnum[]
}

/**
 * Aeronave findMany
 */
export type AeronaveFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Aeronave
   */
  select?: Prisma.AeronaveSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Aeronave
   */
  omit?: Prisma.AeronaveOmit<ExtArgs> | null
  /**
   * Filter, which Aeronaves to fetch.
   */
  where?: Prisma.AeronaveWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Aeronaves to fetch.
   */
  orderBy?: Prisma.AeronaveOrderByWithRelationInput | Prisma.AeronaveOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Aeronaves.
   */
  cursor?: Prisma.AeronaveWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Aeronaves from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Aeronaves.
   */
  skip?: number
  distinct?: Prisma.AeronaveScalarFieldEnum | Prisma.AeronaveScalarFieldEnum[]
}

/**
 * Aeronave create
 */
export type AeronaveCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Aeronave
   */
  select?: Prisma.AeronaveSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Aeronave
   */
  omit?: Prisma.AeronaveOmit<ExtArgs> | null
  /**
   * The data needed to create a Aeronave.
   */
  data: Prisma.XOR<Prisma.AeronaveCreateInput, Prisma.AeronaveUncheckedCreateInput>
}

/**
 * Aeronave createMany
 */
export type AeronaveCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Aeronaves.
   */
  data: Prisma.AeronaveCreateManyInput | Prisma.AeronaveCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Aeronave createManyAndReturn
 */
export type AeronaveCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Aeronave
   */
  select?: Prisma.AeronaveSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Aeronave
   */
  omit?: Prisma.AeronaveOmit<ExtArgs> | null
  /**
   * The data used to create many Aeronaves.
   */
  data: Prisma.AeronaveCreateManyInput | Prisma.AeronaveCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Aeronave update
 */
export type AeronaveUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Aeronave
   */
  select?: Prisma.AeronaveSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Aeronave
   */
  omit?: Prisma.AeronaveOmit<ExtArgs> | null
  /**
   * The data needed to update a Aeronave.
   */
  data: Prisma.XOR<Prisma.AeronaveUpdateInput, Prisma.AeronaveUncheckedUpdateInput>
  /**
   * Choose, which Aeronave to update.
   */
  where: Prisma.AeronaveWhereUniqueInput
}

/**
 * Aeronave updateMany
 */
export type AeronaveUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Aeronaves.
   */
  data: Prisma.XOR<Prisma.AeronaveUpdateManyMutationInput, Prisma.AeronaveUncheckedUpdateManyInput>
  /**
   * Filter which Aeronaves to update
   */
  where?: Prisma.AeronaveWhereInput
  /**
   * Limit how many Aeronaves to update.
   */
  limit?: number
}

/**
 * Aeronave updateManyAndReturn
 */
export type AeronaveUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Aeronave
   */
  select?: Prisma.AeronaveSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Aeronave
   */
  omit?: Prisma.AeronaveOmit<ExtArgs> | null
  /**
   * The data used to update Aeronaves.
   */
  data: Prisma.XOR<Prisma.AeronaveUpdateManyMutationInput, Prisma.AeronaveUncheckedUpdateManyInput>
  /**
   * Filter which Aeronaves to update
   */
  where?: Prisma.AeronaveWhereInput
  /**
   * Limit how many Aeronaves to update.
   */
  limit?: number
}

/**
 * Aeronave upsert
 */
export type AeronaveUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Aeronave
   */
  select?: Prisma.AeronaveSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Aeronave
   */
  omit?: Prisma.AeronaveOmit<ExtArgs> | null
  /**
   * The filter to search for the Aeronave to update in case it exists.
   */
  where: Prisma.AeronaveWhereUniqueInput
  /**
   * In case the Aeronave found by the `where` argument doesn't exist, create a new Aeronave with this data.
   */
  create: Prisma.XOR<Prisma.AeronaveCreateInput, Prisma.AeronaveUncheckedCreateInput>
  /**
   * In case the Aeronave was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AeronaveUpdateInput, Prisma.AeronaveUncheckedUpdateInput>
}

/**
 * Aeronave delete
 */
export type AeronaveDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Aeronave
   */
  select?: Prisma.AeronaveSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Aeronave
   */
  omit?: Prisma.AeronaveOmit<ExtArgs> | null
  /**
   * Filter which Aeronave to delete.
   */
  where: Prisma.AeronaveWhereUniqueInput
}

/**
 * Aeronave deleteMany
 */
export type AeronaveDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Aeronaves to delete
   */
  where?: Prisma.AeronaveWhereInput
  /**
   * Limit how many Aeronaves to delete.
   */
  limit?: number
}

/**
 * Aeronave without action
 */
export type AeronaveDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Aeronave
   */
  select?: Prisma.AeronaveSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Aeronave
   */
  omit?: Prisma.AeronaveOmit<ExtArgs> | null
}
